"use client";
import {useEffect,useState} from 'react';
type Finding={code:string;severity:string;evidence:string;remediation:string};
type Scan={id:string;target:string;status:string;created_at:string;attempts:number;error:string|null;result:{http_status:number;findings:Finding[]}|null};
export default function Dashboard(){
 const [targets,setTargets]=useState<{id:string}[]>([]),[target,setTarget]=useState(''),[scans,setScans]=useState<Scan[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/scans');if(!r.ok)throw Error('Unable to load scan history');setScans(await r.json());setError('');}catch(e){setError(String(e));}}
 useEffect(()=>{fetch('/api/targets').then(async r=>{if(!r.ok)throw Error('Unable to load targets');const t=await r.json();setTargets(t);setTarget(t[0]?.id??'');}).catch(e=>setError(String(e)));void load();const timer=setInterval(load,3000);return()=>clearInterval(timer);},[]);
 async function submit(){setBusy(true);try{const r=await fetch('/api/scans',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({target_id:target})});if(!r.ok)throw Error((await r.json()).detail??'Submission failed');setSelected((await r.json()).id);await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const current=scans.find(s=>s.id===selected)??scans[0];
 return <main><header><span className="eyebrow">ENGINEERING PORTFOLIO / 04</span><h1>Security scanner<span className="dot">.</span></h1><p>HTTP posture checks. Durable jobs. Evidence you can act on.</p></header><section className="controls"><div><label htmlFor="target">Registered target</label><select id="target" value={target} onChange={e=>setTarget(e.target.value)}>{targets.map(t=><option key={t.id}>{t.id}</option>)}</select></div><button disabled={busy||!target} onClick={submit}>{busy?'Submitting…':'Run scan →'}</button><small>One request per scan · No crawling or exploit payloads</small></section>{error&&<p role="alert" className="error">{error}</p>}<div className="grid"><section><h2>Recent scans <span>{scans.length}</span></h2>{scans.length===0&&<p>No scans yet. Choose a demo target to begin.</p>}{scans.map(s=><button className={'scan '+(current?.id===s.id?'active':'')} key={s.id} onClick={()=>setSelected(s.id)}><strong>{s.target}</strong><span className={'badge '+s.status}>{s.status}</span><small>{new Date(s.created_at).toLocaleString()} · attempt {s.attempts}</small></button>)}</section><section><h2>Findings</h2>{!current?<p>Select a scan to view its report.</p>:<><p className="meta">{current.target} · {current.result?`HTTP ${current.result.http_status}`:current.status}</p>{current.error&&<p role="alert">{current.error}</p>}{current.result?<><a className="export" download={`scan-${current.id}.json`} href={'data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(current,null,2))}>Export JSON ↓</a>{current.result.findings.length===0&&<p>No findings under the current policy. This does not establish application security.</p>}{current.result.findings.map((f,i)=><article key={i}><span className={'badge '+f.severity}>{f.severity}</span><h3>{f.code}</h3><p>{f.evidence}</p><p className="remediation">{f.remediation}</p></article>)}</>:<p>Waiting for the worker. Updates every 3 seconds.</p>}</>}</section></div><footer>Demo dashboard · shared tenant · inspect headers, then review findings in context</footer></main>
}
